### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by ggy1992113** [allenlooplee/CcintOcrActivitiesPack#5]
你好，我下载了合合的CcintOcrActicites活动组件，0.3.0版本，在本地安装的时候，报错“[ERROR] [UiPath.Studio.Shared.Logging.OutputLogger] [34] Cannot load assembly: C:\Users\.nuget\packages\ccint.ocr.activities/0.3.0\lib/net461/Ccint.Ocr.dll : System.IO.FileNotFoundException: 未能加载文件或程序集“Cloud.Ocr, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null”或它的某一个依赖项。系统找不到指定的文件。”我该怎末办。求帮助谢谢。

**Comment by allenlooplee** [comment]
你好，这个问题应该是你本地的nuget cache里还没有Ccint OCR包所引用的Cloud OCR包，你可以先到以下地址下载安装：

https://github.com/allenlooplee/CloudOcrActivitiesPack/releases/tag/v0.2.0

后续所有包都会发布到nuget，这样就会自动拉取依赖了。你先试试吧，有问题咱们再讨论。

**Comment by ggy1992113** [comment]
> 你好，这个问题应该是你本地的nuget cache里里没有Ccint OCR包所引用的Cloud OCR包，你可以先到以下地址下载安装：
> 
> https://github.com/allenlooplee/CloudOcrActivitiesPack/releases/tag/v0.2.0
> 
> 后续所有包都会发布到nuget，这样就会自动拉取依赖了。你先试试吧，有问题咱们再讨论。

2.0可以安装，但是3.0还是不行缺少依赖项说是。这个3.0的安装依赖问题神魔时候更新，可以使用。

**Comment by allenlooplee** [comment]
计划这个周末统一处理一下所有包的依赖和版本，然后发布到nuget上。

**Comment by allenlooplee** [comment]
> > 你好，这个问题应该是你本地的nuget cache里里没有Ccint OCR包所引用的Cloud OCR包，你可以先到以下地址下载安装：
> > https://github.com/allenlooplee/CloudOcrActivitiesPack/releases/tag/v0.2.0
> > 后续所有包都会发布到nuget，这样就会自动拉取依赖了。你先试试吧，有问题咱们再讨论。
> 
> 2.0可以安装，但是3.0还是不行缺少依赖项说是。这个3.0的安装依赖问题神魔时候更新，可以使用。

Ccint OCR和Cloud OCR我都已经发布到nuget.org了，后者已经可以搜索，前者还在验证阶段。你现在可以下载[Ccint.Ocr.Activities.0.3.0.nupkg](https://github.com/allenlooplee/CcintOcrActivitiesPack/releases/download/v0.3.0/Ccint.Ocr.Activities.0.3.0.nupkg)来安装，或者等nuget.org显示再安装也行。你只需安装Ccint OCR，UiPath会自动从nuget.org下载并安装Cloud OCR。

另外，在安装之前，你需要先清理一下nuget缓存。你可以打开%userprofile%\. nuget\packages，把Ccint OCR的文件夹删除就可以了。这样做是因为版本号没有变，都是0.3.0。

**Comment by allenlooplee** [comment]
现在可以直接从nuget.org安装Ccint OCR了，在Manage Packages中搜索Ccint.Ocr.Activities就可以看到了，注意选择nuget.org作为安装源，URL是这个https://api.nuget.org/v3/index.json。
